"""index sur published_at et is_critical

Revision ID: 83fe9eb4965c
Revises: 3a5c86c67b02
Create Date: 2026-09-27 02:30:21.089243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fe9eb4965c'
down_revision: Union[str, Sequence[str], None] = '3a5c86c67b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_is_critical'), 'articles', ['is_critical'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_critical'), table_name='articles')
    # ### end Alembic commands ###
